In [1]:
from google.colab import drive
drive.mount('/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /gdrive


In [0]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline 

In [0]:
path = '/gdrive/My Drive/ML:Pilot/Assignments/Data/Fish.csv'

In [0]:
raw_data = pd.read_csv(path)

In [5]:
raw_data.head(10)

Species  Weight  Length1  Length2  Length3   Height   Width
0   Bream   242.0     23.2     25.4     30.0  11.5200  4.0200
1   Bream   290.0     24.0     26.3     31.2  12.4800  4.3056
2   Bream   340.0     23.9     26.5     31.1  12.3778  4.6961
3   Bream   363.0     26.3     29.0     33.5  12.7300  4.4555
4   Bream   430.0     26.5     29.0     34.0  12.4440  5.1340
5   Bream   450.0     26.8     29.7     34.7  13.6024  4.9274
6   Bream   500.0     26.8     29.7     34.5  14.1795  5.2785
7   Bream   390.0     27.6     30.0     35.0  12.6700  4.6900
8   Bream   450.0     27.6     30.0     35.1  14.0049  4.8438
9   Bream   500.0     28.5     30.7     36.2  14.2266  4.9594

In [6]:
raw_data.isnull().sum(axis=0)

Species    0
Weight     0
Length1    0
Length2    0
Length3    0
Height     0
Width      0
dtype: int64

In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
speciesencoder = LabelEncoder()
raw_data["Species"] = speciesencoder.fit_transform(raw_data["Species"])

In [9]:
raw_data.head(10)

Species  Weight  Length1  Length2  Length3   Height   Width
0        0   242.0     23.2     25.4     30.0  11.5200  4.0200
1        0   290.0     24.0     26.3     31.2  12.4800  4.3056
2        0   340.0     23.9     26.5     31.1  12.3778  4.6961
3        0   363.0     26.3     29.0     33.5  12.7300  4.4555
4        0   430.0     26.5     29.0     34.0  12.4440  5.1340
5        0   450.0     26.8     29.7     34.7  13.6024  4.9274
6        0   500.0     26.8     29.7     34.5  14.1795  5.2785
7        0   390.0     27.6     30.0     35.0  12.6700  4.6900
8        0   450.0     27.6     30.0     35.1  14.0049  4.8438
9        0   500.0     28.5     30.7     36.2  14.2266  4.9594

In [0]:
x = raw_data.drop(columns= ['Species'])

In [0]:
y = raw_data["Species"]

In [12]:
x.shape, y.shape, raw_data.shape

((159, 6), (159,), (159, 7))

In [13]:
x.shape,y.shape,raw_data.shape

((159, 6), (159,), (159, 7))

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.25, shuffle = False)

In [16]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((119, 6), (40, 6), (119,), (40,))

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
classifier = KNeighborsClassifier(algorithm= 'brute', n_neighbors=4)

In [19]:
classifier.fit(x_train, y_train)

KNeighborsClassifier(algorithm='brute', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=4, p=2,
                     weights='uniform')

In [0]:
y_pred = classifier.predict(x_test)

In [0]:
from sklearn.metrics import classification_report, confusion_matrix

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           2       0.10      0.22      0.13         9
           3       0.00      0.00      0.00        17
           5       0.00      0.00      0.00        14

    accuracy                           0.05        40
   macro avg       0.02      0.06      0.03        40
weighted avg       0.02      0.05      0.03        40



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [23]:
print(confusion_matrix(y_test, y_pred))

[[ 0  0  0  0]
 [ 7  2  0  0]
 [12  5  0  0]
 [ 0 14  0  0]]
